### ISSUE TITLE
Error: Failed to fetch

### ISSUE THREAD

**Issue by Xiaothecar** [Nitrrine/have-i-been-scraped-by-spy-pet#1]
Error : Failed to fetch.
I can't add kickthespy bot, and when i try out the websites it constantly can't do it. I provided both the ID and Invite, yet nothing happened, only the error message is popping up.

**Comment by Nitrrine** [comment]
Hello! Please send me a screenshot of a page with error.

**Comment by shinob1kai** [comment]
Hi there, Here is a Screenshot from the Error.
![Screenshot 2024-06-22 231557](https://github.com/Nitrrine/have-i-been-scraped-by-spy-pet/assets/120254902/ffbfdeda-d110-47c8-a795-f50948db9c2a)

**Comment by Nitrrine** [comment]
kickthespy.pet blocks us access to make a requests to their API, because of CORS, use ThatSINEWAVE/Spy.pet-Info as provider for now.
